/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.financeai.promptResponse.model.ResponseDataEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseCandlestickChart
 */

public class ResponseCandlestickChart {
  @JsonProperty("data")
  private List<ResponseDataEntryItem> data = new ArrayList<>();

  public ResponseCandlestickChart data(List<ResponseDataEntryItem> data) {
    this.data = data;
    return this;
  }

  public ResponseCandlestickChart addDataItem(ResponseDataEntryItem dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  public List<ResponseDataEntryItem> getData() {
    return data;
  }

  public void setData(List<ResponseDataEntryItem> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCandlestickChart Response_candlestickChart = (ResponseCandlestickChart) o;
    return Objects.equals(this.data, Response_candlestickChart.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCandlestickChart {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
