/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.financeai.promptResponse.model.ResponseMonthlyDataEntryItem;
import com.wavemaker.financeai.promptResponse.model.ResponseThisweekEntryItem;
import com.wavemaker.financeai.promptResponse.model.ResponseWeeklyDataEntryItem;
import com.wavemaker.financeai.promptResponse.model.ResponseYearlyData;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseLineChart
 */

public class ResponseLineChart {
  @JsonProperty("weeklyData")
  private List<ResponseWeeklyDataEntryItem> weeklyData = new ArrayList<>();

  @JsonProperty("monthlyData")
  private List<ResponseMonthlyDataEntryItem> monthlyData = new ArrayList<>();

  @JsonProperty("yearlyData")
  private ResponseYearlyData yearlyData = null;

  @JsonProperty("thisweek")
  private List<ResponseThisweekEntryItem> thisweek = new ArrayList<>();

  public ResponseLineChart weeklyData(List<ResponseWeeklyDataEntryItem> weeklyData) {
    this.weeklyData = weeklyData;
    return this;
  }

  public ResponseLineChart addWeeklyDataItem(ResponseWeeklyDataEntryItem weeklyDataItem) {
    this.weeklyData.add(weeklyDataItem);
    return this;
  }

   /**
   * Get weeklyData
   * @return weeklyData
  **/
  public List<ResponseWeeklyDataEntryItem> getWeeklyData() {
    return weeklyData;
  }

  public void setWeeklyData(List<ResponseWeeklyDataEntryItem> weeklyData) {
    this.weeklyData = weeklyData;
  }

  public ResponseLineChart monthlyData(List<ResponseMonthlyDataEntryItem> monthlyData) {
    this.monthlyData = monthlyData;
    return this;
  }

  public ResponseLineChart addMonthlyDataItem(ResponseMonthlyDataEntryItem monthlyDataItem) {
    this.monthlyData.add(monthlyDataItem);
    return this;
  }

   /**
   * Get monthlyData
   * @return monthlyData
  **/
  public List<ResponseMonthlyDataEntryItem> getMonthlyData() {
    return monthlyData;
  }

  public void setMonthlyData(List<ResponseMonthlyDataEntryItem> monthlyData) {
    this.monthlyData = monthlyData;
  }

  public ResponseLineChart yearlyData(ResponseYearlyData yearlyData) {
    this.yearlyData = yearlyData;
    return this;
  }

   /**
   * Get yearlyData
   * @return yearlyData
  **/
  public ResponseYearlyData getYearlyData() {
    return yearlyData;
  }

  public void setYearlyData(ResponseYearlyData yearlyData) {
    this.yearlyData = yearlyData;
  }

  public ResponseLineChart thisweek(List<ResponseThisweekEntryItem> thisweek) {
    this.thisweek = thisweek;
    return this;
  }

  public ResponseLineChart addThisweekItem(ResponseThisweekEntryItem thisweekItem) {
    this.thisweek.add(thisweekItem);
    return this;
  }

   /**
   * Get thisweek
   * @return thisweek
  **/
  public List<ResponseThisweekEntryItem> getThisweek() {
    return thisweek;
  }

  public void setThisweek(List<ResponseThisweekEntryItem> thisweek) {
    this.thisweek = thisweek;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseLineChart Response_lineChart = (ResponseLineChart) o;
    return Objects.equals(this.weeklyData, Response_lineChart.weeklyData) &&
        Objects.equals(this.monthlyData, Response_lineChart.monthlyData) &&
        Objects.equals(this.yearlyData, Response_lineChart.yearlyData) &&
        Objects.equals(this.thisweek, Response_lineChart.thisweek);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weeklyData, monthlyData, yearlyData, thisweek);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseLineChart {\n");
    
    sb.append("    weeklyData: ").append(toIndentedString(weeklyData)).append("\n");
    sb.append("    monthlyData: ").append(toIndentedString(monthlyData)).append("\n");
    sb.append("    yearlyData: ").append(toIndentedString(yearlyData)).append("\n");
    sb.append("    thisweek: ").append(toIndentedString(thisweek)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
