/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseMonthlyDataEntryItem
 */

public class ResponseMonthlyDataEntryItem {
  @JsonProperty("month")
  private String month = null;

  @JsonProperty("averageClose")
  private Double averageClose = null;

  public ResponseMonthlyDataEntryItem month(String month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public ResponseMonthlyDataEntryItem averageClose(Double averageClose) {
    this.averageClose = averageClose;
    return this;
  }

   /**
   * Get averageClose
   * @return averageClose
  **/
  public Double getAverageClose() {
    return averageClose;
  }

  public void setAverageClose(Double averageClose) {
    this.averageClose = averageClose;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMonthlyDataEntryItem Response_monthlyDataEntryItem = (ResponseMonthlyDataEntryItem) o;
    return Objects.equals(this.month, Response_monthlyDataEntryItem.month) &&
        Objects.equals(this.averageClose, Response_monthlyDataEntryItem.averageClose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(month, averageClose);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMonthlyDataEntryItem {\n");
    
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    averageClose: ").append(toIndentedString(averageClose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
