/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * Response5YearEntryItem
 */

public class Response5YearEntryItem {
  @JsonProperty("year")
  private String year = null;

  @JsonProperty("averageClose")
  private Double averageClose = null;

  public Response5YearEntryItem year(String year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }

  public Response5YearEntryItem averageClose(Double averageClose) {
    this.averageClose = averageClose;
    return this;
  }

   /**
   * Get averageClose
   * @return averageClose
  **/
  public Double getAverageClose() {
    return averageClose;
  }

  public void setAverageClose(Double averageClose) {
    this.averageClose = averageClose;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response5YearEntryItem Response_5YearEntryItem = (Response5YearEntryItem) o;
    return Objects.equals(this.year, Response_5YearEntryItem.year) &&
        Objects.equals(this.averageClose, Response_5YearEntryItem.averageClose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, averageClose);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response5YearEntryItem {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    averageClose: ").append(toIndentedString(averageClose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
