/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseDataEntryItem
 */

public class ResponseDataEntryItem {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("Net Income")
  private String Net_Income = null;

  @JsonProperty("high")
  private Double high = null;

  @JsonProperty("Year")
  private String Year = null;

  @JsonProperty("low")
  private Double low = null;

  @JsonProperty("Operating Margin")
  private String Operating_Margin = null;

  @JsonProperty("EPS")
  private String EPS = null;

  @JsonProperty("Revenue")
  private String Revenue = null;

  @JsonProperty("close")
  private Double close = null;

  @JsonProperty("open")
  private Double open = null;

  public ResponseDataEntryItem date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ResponseDataEntryItem Net_Income(String Net_Income) {
    this.Net_Income = Net_Income;
    return this;
  }

   /**
   * Get Net_Income
   * @return Net_Income
  **/
  public String getNetIncome() {
    return Net_Income;
  }

  public void setNetIncome(String Net_Income) {
    this.Net_Income = Net_Income;
  }

  public ResponseDataEntryItem high(Double high) {
    this.high = high;
    return this;
  }

   /**
   * Get high
   * @return high
  **/
  public Double getHigh() {
    return high;
  }

  public void setHigh(Double high) {
    this.high = high;
  }

  public ResponseDataEntryItem Year(String Year) {
    this.Year = Year;
    return this;
  }

   /**
   * Get Year
   * @return Year
  **/
  public String getYear() {
    return Year;
  }

  public void setYear(String Year) {
    this.Year = Year;
  }

  public ResponseDataEntryItem low(Double low) {
    this.low = low;
    return this;
  }

   /**
   * Get low
   * @return low
  **/
  public Double getLow() {
    return low;
  }

  public void setLow(Double low) {
    this.low = low;
  }

  public ResponseDataEntryItem Operating_Margin(String Operating_Margin) {
    this.Operating_Margin = Operating_Margin;
    return this;
  }

   /**
   * Get Operating_Margin
   * @return Operating_Margin
  **/
  public String getOperatingMargin() {
    return Operating_Margin;
  }

  public void setOperatingMargin(String Operating_Margin) {
    this.Operating_Margin = Operating_Margin;
  }

  public ResponseDataEntryItem EPS(String EPS) {
    this.EPS = EPS;
    return this;
  }

   /**
   * Get EPS
   * @return EPS
  **/
  public String getEPS() {
    return EPS;
  }

  public void setEPS(String EPS) {
    this.EPS = EPS;
  }

  public ResponseDataEntryItem Revenue(String Revenue) {
    this.Revenue = Revenue;
    return this;
  }

   /**
   * Get Revenue
   * @return Revenue
  **/
  public String getRevenue() {
    return Revenue;
  }

  public void setRevenue(String Revenue) {
    this.Revenue = Revenue;
  }

  public ResponseDataEntryItem close(Double close) {
    this.close = close;
    return this;
  }

   /**
   * Get close
   * @return close
  **/
  public Double getClose() {
    return close;
  }

  public void setClose(Double close) {
    this.close = close;
  }

  public ResponseDataEntryItem open(Double open) {
    this.open = open;
    return this;
  }

   /**
   * Get open
   * @return open
  **/
  public Double getOpen() {
    return open;
  }

  public void setOpen(Double open) {
    this.open = open;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDataEntryItem Response_dataEntryItem = (ResponseDataEntryItem) o;
    return Objects.equals(this.date, Response_dataEntryItem.date) &&
        Objects.equals(this.Net_Income, Response_dataEntryItem.Net_Income) &&
        Objects.equals(this.high, Response_dataEntryItem.high) &&
        Objects.equals(this.Year, Response_dataEntryItem.Year) &&
        Objects.equals(this.low, Response_dataEntryItem.low) &&
        Objects.equals(this.Operating_Margin, Response_dataEntryItem.Operating_Margin) &&
        Objects.equals(this.EPS, Response_dataEntryItem.EPS) &&
        Objects.equals(this.Revenue, Response_dataEntryItem.Revenue) &&
        Objects.equals(this.close, Response_dataEntryItem.close) &&
        Objects.equals(this.open, Response_dataEntryItem.open);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, Net_Income, high, Year, low, Operating_Margin, EPS, Revenue, close, open);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDataEntryItem {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    Net_Income: ").append(toIndentedString(Net_Income)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    Year: ").append(toIndentedString(Year)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    Operating_Margin: ").append(toIndentedString(Operating_Margin)).append("\n");
    sb.append("    EPS: ").append(toIndentedString(EPS)).append("\n");
    sb.append("    Revenue: ").append(toIndentedString(Revenue)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
