/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.promptResponse.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.financeai.promptResponse.model.Response10YearEntryItem;
import com.wavemaker.financeai.promptResponse.model.Response3YearEntryItem;
import com.wavemaker.financeai.promptResponse.model.Response5YearEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseYearlyData
 */

public class ResponseYearlyData {
  @JsonProperty("5Year")
  private List<Response5YearEntryItem> _5year = new ArrayList<>();

  @JsonProperty("10Year")
  private List<Response10YearEntryItem> _10Year = new ArrayList<>();

  @JsonProperty("3Year")
  private List<Response3YearEntryItem> _3year = new ArrayList<>();

  public ResponseYearlyData _5year(List<Response5YearEntryItem> _5year) {
    this._5year = _5year;
    return this;
  }

  public ResponseYearlyData add5yearItem(Response5YearEntryItem _5yearItem) {
    this._5year.add(_5yearItem);
    return this;
  }

   /**
   * Get _5year
   * @return _5year
  **/
  public List<Response5YearEntryItem> get5year() {
    return _5year;
  }

  public void set5year(List<Response5YearEntryItem> _5year) {
    this._5year = _5year;
  }

  public ResponseYearlyData _10Year(List<Response10YearEntryItem> _10Year) {
    this._10Year = _10Year;
    return this;
  }

  public ResponseYearlyData add10YearItem(Response10YearEntryItem _10YearItem) {
    this._10Year.add(_10YearItem);
    return this;
  }

   /**
   * Get _10Year
   * @return _10Year
  **/
  public List<Response10YearEntryItem> get10Year() {
    return _10Year;
  }

  public void set10Year(List<Response10YearEntryItem> _10Year) {
    this._10Year = _10Year;
  }

  public ResponseYearlyData _3year(List<Response3YearEntryItem> _3year) {
    this._3year = _3year;
    return this;
  }

  public ResponseYearlyData add3yearItem(Response3YearEntryItem _3yearItem) {
    this._3year.add(_3yearItem);
    return this;
  }

   /**
   * Get _3year
   * @return _3year
  **/
  public List<Response3YearEntryItem> get3year() {
    return _3year;
  }

  public void set3year(List<Response3YearEntryItem> _3year) {
    this._3year = _3year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseYearlyData Response_yearlyData = (ResponseYearlyData) o;
    return Objects.equals(this._5year, Response_yearlyData._5year) &&
        Objects.equals(this._10Year, Response_yearlyData._10Year) &&
        Objects.equals(this._3year, Response_yearlyData._3year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_5year, _10Year, _3year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseYearlyData {\n");
    
    sb.append("    _5year: ").append(toIndentedString(_5year)).append("\n");
    sb.append("    _10Year: ").append(toIndentedString(_10Year)).append("\n");
    sb.append("    _3year: ").append(toIndentedString(_3year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
