/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.sectorRotation.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseChange
 */

public class ResponseChange {
  @JsonProperty("07-18-2025")
  private Integer _07_18_2025 = null;

  @JsonProperty("07-22-2025")
  private Integer _07_22_2025 = null;

  @JsonProperty("07-25-2025")
  private Integer _07_25_2025 = null;

  @JsonProperty("07-16-2025")
  private Integer _07_16_2025 = null;

  @JsonProperty("07-24-2025")
  private Integer _07_24_2025 = null;

  @JsonProperty("07-17-2025")
  private Integer _07_17_2025 = null;

  @JsonProperty("07-23-2025")
  private Integer _07_23_2025 = null;

  @JsonProperty("07-21-2025")
  private Integer _07_21_2025 = null;

  public ResponseChange _07_18_2025(Integer _07_18_2025) {
    this._07_18_2025 = _07_18_2025;
    return this;
  }

   /**
   * Get _07_18_2025
   * @return _07_18_2025
  **/
  public Integer get07182025() {
    return _07_18_2025;
  }

  public void set07182025(Integer _07_18_2025) {
    this._07_18_2025 = _07_18_2025;
  }

  public ResponseChange _07_22_2025(Integer _07_22_2025) {
    this._07_22_2025 = _07_22_2025;
    return this;
  }

   /**
   * Get _07_22_2025
   * @return _07_22_2025
  **/
  public Integer get07222025() {
    return _07_22_2025;
  }

  public void set07222025(Integer _07_22_2025) {
    this._07_22_2025 = _07_22_2025;
  }

  public ResponseChange _07_25_2025(Integer _07_25_2025) {
    this._07_25_2025 = _07_25_2025;
    return this;
  }

   /**
   * Get _07_25_2025
   * @return _07_25_2025
  **/
  public Integer get07252025() {
    return _07_25_2025;
  }

  public void set07252025(Integer _07_25_2025) {
    this._07_25_2025 = _07_25_2025;
  }

  public ResponseChange _07_16_2025(Integer _07_16_2025) {
    this._07_16_2025 = _07_16_2025;
    return this;
  }

   /**
   * Get _07_16_2025
   * @return _07_16_2025
  **/
  public Integer get07162025() {
    return _07_16_2025;
  }

  public void set07162025(Integer _07_16_2025) {
    this._07_16_2025 = _07_16_2025;
  }

  public ResponseChange _07_24_2025(Integer _07_24_2025) {
    this._07_24_2025 = _07_24_2025;
    return this;
  }

   /**
   * Get _07_24_2025
   * @return _07_24_2025
  **/
  public Integer get07242025() {
    return _07_24_2025;
  }

  public void set07242025(Integer _07_24_2025) {
    this._07_24_2025 = _07_24_2025;
  }

  public ResponseChange _07_17_2025(Integer _07_17_2025) {
    this._07_17_2025 = _07_17_2025;
    return this;
  }

   /**
   * Get _07_17_2025
   * @return _07_17_2025
  **/
  public Integer get07172025() {
    return _07_17_2025;
  }

  public void set07172025(Integer _07_17_2025) {
    this._07_17_2025 = _07_17_2025;
  }

  public ResponseChange _07_23_2025(Integer _07_23_2025) {
    this._07_23_2025 = _07_23_2025;
    return this;
  }

   /**
   * Get _07_23_2025
   * @return _07_23_2025
  **/
  public Integer get07232025() {
    return _07_23_2025;
  }

  public void set07232025(Integer _07_23_2025) {
    this._07_23_2025 = _07_23_2025;
  }

  public ResponseChange _07_21_2025(Integer _07_21_2025) {
    this._07_21_2025 = _07_21_2025;
    return this;
  }

   /**
   * Get _07_21_2025
   * @return _07_21_2025
  **/
  public Integer get07212025() {
    return _07_21_2025;
  }

  public void set07212025(Integer _07_21_2025) {
    this._07_21_2025 = _07_21_2025;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseChange Response_change = (ResponseChange) o;
    return Objects.equals(this._07_18_2025, Response_change._07_18_2025) &&
        Objects.equals(this._07_22_2025, Response_change._07_22_2025) &&
        Objects.equals(this._07_25_2025, Response_change._07_25_2025) &&
        Objects.equals(this._07_16_2025, Response_change._07_16_2025) &&
        Objects.equals(this._07_24_2025, Response_change._07_24_2025) &&
        Objects.equals(this._07_17_2025, Response_change._07_17_2025) &&
        Objects.equals(this._07_23_2025, Response_change._07_23_2025) &&
        Objects.equals(this._07_21_2025, Response_change._07_21_2025);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_07_18_2025, _07_22_2025, _07_25_2025, _07_16_2025, _07_24_2025, _07_17_2025, _07_23_2025, _07_21_2025);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseChange {\n");
    
    sb.append("    _07_18_2025: ").append(toIndentedString(_07_18_2025)).append("\n");
    sb.append("    _07_22_2025: ").append(toIndentedString(_07_22_2025)).append("\n");
    sb.append("    _07_25_2025: ").append(toIndentedString(_07_25_2025)).append("\n");
    sb.append("    _07_16_2025: ").append(toIndentedString(_07_16_2025)).append("\n");
    sb.append("    _07_24_2025: ").append(toIndentedString(_07_24_2025)).append("\n");
    sb.append("    _07_17_2025: ").append(toIndentedString(_07_17_2025)).append("\n");
    sb.append("    _07_23_2025: ").append(toIndentedString(_07_23_2025)).append("\n");
    sb.append("    _07_21_2025: ").append(toIndentedString(_07_21_2025)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
