/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.indicesInfo.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseIndicesEntryItem
 */

public class ResponseIndicesEntryItem {
  @JsonProperty("ticker")
  private String ticker = null;

  @JsonProperty("last_updated")
  private String last_updated = null;

  @JsonProperty("change")
  private String change = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("logo")
  private String logo = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("percent_change")
  private String percent_change = null;

  public ResponseIndicesEntryItem ticker(String ticker) {
    this.ticker = ticker;
    return this;
  }

   /**
   * Get ticker
   * @return ticker
  **/
  public String getTicker() {
    return ticker;
  }

  public void setTicker(String ticker) {
    this.ticker = ticker;
  }

  public ResponseIndicesEntryItem last_updated(String last_updated) {
    this.last_updated = last_updated;
    return this;
  }

   /**
   * Get last_updated
   * @return last_updated
  **/
  public String getLastUpdated() {
    return last_updated;
  }

  public void setLastUpdated(String last_updated) {
    this.last_updated = last_updated;
  }

  public ResponseIndicesEntryItem change(String change) {
    this.change = change;
    return this;
  }

   /**
   * Get change
   * @return change
  **/
  public String getChange() {
    return change;
  }

  public void setChange(String change) {
    this.change = change;
  }

  public ResponseIndicesEntryItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponseIndicesEntryItem logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public ResponseIndicesEntryItem value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public ResponseIndicesEntryItem percent_change(String percent_change) {
    this.percent_change = percent_change;
    return this;
  }

   /**
   * Get percent_change
   * @return percent_change
  **/
  public String getPercentChange() {
    return percent_change;
  }

  public void setPercentChange(String percent_change) {
    this.percent_change = percent_change;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIndicesEntryItem Response_indicesEntryItem = (ResponseIndicesEntryItem) o;
    return Objects.equals(this.ticker, Response_indicesEntryItem.ticker) &&
        Objects.equals(this.last_updated, Response_indicesEntryItem.last_updated) &&
        Objects.equals(this.change, Response_indicesEntryItem.change) &&
        Objects.equals(this.name, Response_indicesEntryItem.name) &&
        Objects.equals(this.logo, Response_indicesEntryItem.logo) &&
        Objects.equals(this.value, Response_indicesEntryItem.value) &&
        Objects.equals(this.percent_change, Response_indicesEntryItem.percent_change);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticker, last_updated, change, name, logo, value, percent_change);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIndicesEntryItem {\n");
    
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    last_updated: ").append(toIndentedString(last_updated)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    percent_change: ").append(toIndentedString(percent_change)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
