/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.yearlyOutperformers.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("2012")
  private String _2012 = null;

  @JsonProperty("2011")
  private String _2011 = null;

  @JsonProperty("2010")
  private String _2010 = null;

  @JsonProperty("2009")
  private String _2009 = null;

  @JsonProperty("2008")
  private String _2008 = null;

  @JsonProperty("2007")
  private String _2007 = null;

  @JsonProperty("scriptCode")
  private String scriptCode = null;

  @JsonProperty("2006")
  private String _2006 = null;

  @JsonProperty("2005")
  private String _2005 = null;

  @JsonProperty("2004")
  private String _2004 = null;

  @JsonProperty("2003")
  private String _2003 = null;

  @JsonProperty("2025")
  private String _2025 = null;

  @JsonProperty("2002")
  private String _2002 = null;

  @JsonProperty("2024")
  private String _2024 = null;

  @JsonProperty("2001")
  private String _2001 = null;

  @JsonProperty("2023")
  private String _2023 = null;

  @JsonProperty("2000")
  private String _2000 = null;

  @JsonProperty("2022")
  private String _2022 = null;

  @JsonProperty("2021")
  private String _2021 = null;

  @JsonProperty("2020")
  private String _2020 = null;

  @JsonProperty("2019")
  private String _2019 = null;

  @JsonProperty("2018")
  private String _2018 = null;

  @JsonProperty("2017")
  private String _2017 = null;

  @JsonProperty("2016")
  private String _2016 = null;

  @JsonProperty("2015")
  private String _2015 = null;

  @JsonProperty("2014")
  private String _2014 = null;

  @JsonProperty("2013")
  private String _2013 = null;

  @JsonProperty("scriptName")
  private String scriptName = null;

  public ResponseRootResponseROOTEntryItem _2012(String _2012) {
    this._2012 = _2012;
    return this;
  }

   /**
   * Get _2012
   * @return _2012
  **/
  public String get2012() {
    return _2012;
  }

  public void set2012(String _2012) {
    this._2012 = _2012;
  }

  public ResponseRootResponseROOTEntryItem _2011(String _2011) {
    this._2011 = _2011;
    return this;
  }

   /**
   * Get _2011
   * @return _2011
  **/
  public String get2011() {
    return _2011;
  }

  public void set2011(String _2011) {
    this._2011 = _2011;
  }

  public ResponseRootResponseROOTEntryItem _2010(String _2010) {
    this._2010 = _2010;
    return this;
  }

   /**
   * Get _2010
   * @return _2010
  **/
  public String get2010() {
    return _2010;
  }

  public void set2010(String _2010) {
    this._2010 = _2010;
  }

  public ResponseRootResponseROOTEntryItem _2009(String _2009) {
    this._2009 = _2009;
    return this;
  }

   /**
   * Get _2009
   * @return _2009
  **/
  public String get2009() {
    return _2009;
  }

  public void set2009(String _2009) {
    this._2009 = _2009;
  }

  public ResponseRootResponseROOTEntryItem _2008(String _2008) {
    this._2008 = _2008;
    return this;
  }

   /**
   * Get _2008
   * @return _2008
  **/
  public String get2008() {
    return _2008;
  }

  public void set2008(String _2008) {
    this._2008 = _2008;
  }

  public ResponseRootResponseROOTEntryItem _2007(String _2007) {
    this._2007 = _2007;
    return this;
  }

   /**
   * Get _2007
   * @return _2007
  **/
  public String get2007() {
    return _2007;
  }

  public void set2007(String _2007) {
    this._2007 = _2007;
  }

  public ResponseRootResponseROOTEntryItem scriptCode(String scriptCode) {
    this.scriptCode = scriptCode;
    return this;
  }

   /**
   * Get scriptCode
   * @return scriptCode
  **/
  public String getScriptCode() {
    return scriptCode;
  }

  public void setScriptCode(String scriptCode) {
    this.scriptCode = scriptCode;
  }

  public ResponseRootResponseROOTEntryItem _2006(String _2006) {
    this._2006 = _2006;
    return this;
  }

   /**
   * Get _2006
   * @return _2006
  **/
  public String get2006() {
    return _2006;
  }

  public void set2006(String _2006) {
    this._2006 = _2006;
  }

  public ResponseRootResponseROOTEntryItem _2005(String _2005) {
    this._2005 = _2005;
    return this;
  }

   /**
   * Get _2005
   * @return _2005
  **/
  public String get2005() {
    return _2005;
  }

  public void set2005(String _2005) {
    this._2005 = _2005;
  }

  public ResponseRootResponseROOTEntryItem _2004(String _2004) {
    this._2004 = _2004;
    return this;
  }

   /**
   * Get _2004
   * @return _2004
  **/
  public String get2004() {
    return _2004;
  }

  public void set2004(String _2004) {
    this._2004 = _2004;
  }

  public ResponseRootResponseROOTEntryItem _2003(String _2003) {
    this._2003 = _2003;
    return this;
  }

   /**
   * Get _2003
   * @return _2003
  **/
  public String get2003() {
    return _2003;
  }

  public void set2003(String _2003) {
    this._2003 = _2003;
  }

  public ResponseRootResponseROOTEntryItem _2025(String _2025) {
    this._2025 = _2025;
    return this;
  }

   /**
   * Get _2025
   * @return _2025
  **/
  public String get2025() {
    return _2025;
  }

  public void set2025(String _2025) {
    this._2025 = _2025;
  }

  public ResponseRootResponseROOTEntryItem _2002(String _2002) {
    this._2002 = _2002;
    return this;
  }

   /**
   * Get _2002
   * @return _2002
  **/
  public String get2002() {
    return _2002;
  }

  public void set2002(String _2002) {
    this._2002 = _2002;
  }

  public ResponseRootResponseROOTEntryItem _2024(String _2024) {
    this._2024 = _2024;
    return this;
  }

   /**
   * Get _2024
   * @return _2024
  **/
  public String get2024() {
    return _2024;
  }

  public void set2024(String _2024) {
    this._2024 = _2024;
  }

  public ResponseRootResponseROOTEntryItem _2001(String _2001) {
    this._2001 = _2001;
    return this;
  }

   /**
   * Get _2001
   * @return _2001
  **/
  public String get2001() {
    return _2001;
  }

  public void set2001(String _2001) {
    this._2001 = _2001;
  }

  public ResponseRootResponseROOTEntryItem _2023(String _2023) {
    this._2023 = _2023;
    return this;
  }

   /**
   * Get _2023
   * @return _2023
  **/
  public String get2023() {
    return _2023;
  }

  public void set2023(String _2023) {
    this._2023 = _2023;
  }

  public ResponseRootResponseROOTEntryItem _2000(String _2000) {
    this._2000 = _2000;
    return this;
  }

   /**
   * Get _2000
   * @return _2000
  **/
  public String get2000() {
    return _2000;
  }

  public void set2000(String _2000) {
    this._2000 = _2000;
  }

  public ResponseRootResponseROOTEntryItem _2022(String _2022) {
    this._2022 = _2022;
    return this;
  }

   /**
   * Get _2022
   * @return _2022
  **/
  public String get2022() {
    return _2022;
  }

  public void set2022(String _2022) {
    this._2022 = _2022;
  }

  public ResponseRootResponseROOTEntryItem _2021(String _2021) {
    this._2021 = _2021;
    return this;
  }

   /**
   * Get _2021
   * @return _2021
  **/
  public String get2021() {
    return _2021;
  }

  public void set2021(String _2021) {
    this._2021 = _2021;
  }

  public ResponseRootResponseROOTEntryItem _2020(String _2020) {
    this._2020 = _2020;
    return this;
  }

   /**
   * Get _2020
   * @return _2020
  **/
  public String get2020() {
    return _2020;
  }

  public void set2020(String _2020) {
    this._2020 = _2020;
  }

  public ResponseRootResponseROOTEntryItem _2019(String _2019) {
    this._2019 = _2019;
    return this;
  }

   /**
   * Get _2019
   * @return _2019
  **/
  public String get2019() {
    return _2019;
  }

  public void set2019(String _2019) {
    this._2019 = _2019;
  }

  public ResponseRootResponseROOTEntryItem _2018(String _2018) {
    this._2018 = _2018;
    return this;
  }

   /**
   * Get _2018
   * @return _2018
  **/
  public String get2018() {
    return _2018;
  }

  public void set2018(String _2018) {
    this._2018 = _2018;
  }

  public ResponseRootResponseROOTEntryItem _2017(String _2017) {
    this._2017 = _2017;
    return this;
  }

   /**
   * Get _2017
   * @return _2017
  **/
  public String get2017() {
    return _2017;
  }

  public void set2017(String _2017) {
    this._2017 = _2017;
  }

  public ResponseRootResponseROOTEntryItem _2016(String _2016) {
    this._2016 = _2016;
    return this;
  }

   /**
   * Get _2016
   * @return _2016
  **/
  public String get2016() {
    return _2016;
  }

  public void set2016(String _2016) {
    this._2016 = _2016;
  }

  public ResponseRootResponseROOTEntryItem _2015(String _2015) {
    this._2015 = _2015;
    return this;
  }

   /**
   * Get _2015
   * @return _2015
  **/
  public String get2015() {
    return _2015;
  }

  public void set2015(String _2015) {
    this._2015 = _2015;
  }

  public ResponseRootResponseROOTEntryItem _2014(String _2014) {
    this._2014 = _2014;
    return this;
  }

   /**
   * Get _2014
   * @return _2014
  **/
  public String get2014() {
    return _2014;
  }

  public void set2014(String _2014) {
    this._2014 = _2014;
  }

  public ResponseRootResponseROOTEntryItem _2013(String _2013) {
    this._2013 = _2013;
    return this;
  }

   /**
   * Get _2013
   * @return _2013
  **/
  public String get2013() {
    return _2013;
  }

  public void set2013(String _2013) {
    this._2013 = _2013;
  }

  public ResponseRootResponseROOTEntryItem scriptName(String scriptName) {
    this.scriptName = scriptName;
    return this;
  }

   /**
   * Get scriptName
   * @return scriptName
  **/
  public String getScriptName() {
    return scriptName;
  }

  public void setScriptName(String scriptName) {
    this.scriptName = scriptName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this._2012, Response_RootResponseROOTEntryItem._2012) &&
        Objects.equals(this._2011, Response_RootResponseROOTEntryItem._2011) &&
        Objects.equals(this._2010, Response_RootResponseROOTEntryItem._2010) &&
        Objects.equals(this._2009, Response_RootResponseROOTEntryItem._2009) &&
        Objects.equals(this._2008, Response_RootResponseROOTEntryItem._2008) &&
        Objects.equals(this._2007, Response_RootResponseROOTEntryItem._2007) &&
        Objects.equals(this.scriptCode, Response_RootResponseROOTEntryItem.scriptCode) &&
        Objects.equals(this._2006, Response_RootResponseROOTEntryItem._2006) &&
        Objects.equals(this._2005, Response_RootResponseROOTEntryItem._2005) &&
        Objects.equals(this._2004, Response_RootResponseROOTEntryItem._2004) &&
        Objects.equals(this._2003, Response_RootResponseROOTEntryItem._2003) &&
        Objects.equals(this._2025, Response_RootResponseROOTEntryItem._2025) &&
        Objects.equals(this._2002, Response_RootResponseROOTEntryItem._2002) &&
        Objects.equals(this._2024, Response_RootResponseROOTEntryItem._2024) &&
        Objects.equals(this._2001, Response_RootResponseROOTEntryItem._2001) &&
        Objects.equals(this._2023, Response_RootResponseROOTEntryItem._2023) &&
        Objects.equals(this._2000, Response_RootResponseROOTEntryItem._2000) &&
        Objects.equals(this._2022, Response_RootResponseROOTEntryItem._2022) &&
        Objects.equals(this._2021, Response_RootResponseROOTEntryItem._2021) &&
        Objects.equals(this._2020, Response_RootResponseROOTEntryItem._2020) &&
        Objects.equals(this._2019, Response_RootResponseROOTEntryItem._2019) &&
        Objects.equals(this._2018, Response_RootResponseROOTEntryItem._2018) &&
        Objects.equals(this._2017, Response_RootResponseROOTEntryItem._2017) &&
        Objects.equals(this._2016, Response_RootResponseROOTEntryItem._2016) &&
        Objects.equals(this._2015, Response_RootResponseROOTEntryItem._2015) &&
        Objects.equals(this._2014, Response_RootResponseROOTEntryItem._2014) &&
        Objects.equals(this._2013, Response_RootResponseROOTEntryItem._2013) &&
        Objects.equals(this.scriptName, Response_RootResponseROOTEntryItem.scriptName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_2012, _2011, _2010, _2009, _2008, _2007, scriptCode, _2006, _2005, _2004, _2003, _2025, _2002, _2024, _2001, _2023, _2000, _2022, _2021, _2020, _2019, _2018, _2017, _2016, _2015, _2014, _2013, scriptName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    _2012: ").append(toIndentedString(_2012)).append("\n");
    sb.append("    _2011: ").append(toIndentedString(_2011)).append("\n");
    sb.append("    _2010: ").append(toIndentedString(_2010)).append("\n");
    sb.append("    _2009: ").append(toIndentedString(_2009)).append("\n");
    sb.append("    _2008: ").append(toIndentedString(_2008)).append("\n");
    sb.append("    _2007: ").append(toIndentedString(_2007)).append("\n");
    sb.append("    scriptCode: ").append(toIndentedString(scriptCode)).append("\n");
    sb.append("    _2006: ").append(toIndentedString(_2006)).append("\n");
    sb.append("    _2005: ").append(toIndentedString(_2005)).append("\n");
    sb.append("    _2004: ").append(toIndentedString(_2004)).append("\n");
    sb.append("    _2003: ").append(toIndentedString(_2003)).append("\n");
    sb.append("    _2025: ").append(toIndentedString(_2025)).append("\n");
    sb.append("    _2002: ").append(toIndentedString(_2002)).append("\n");
    sb.append("    _2024: ").append(toIndentedString(_2024)).append("\n");
    sb.append("    _2001: ").append(toIndentedString(_2001)).append("\n");
    sb.append("    _2023: ").append(toIndentedString(_2023)).append("\n");
    sb.append("    _2000: ").append(toIndentedString(_2000)).append("\n");
    sb.append("    _2022: ").append(toIndentedString(_2022)).append("\n");
    sb.append("    _2021: ").append(toIndentedString(_2021)).append("\n");
    sb.append("    _2020: ").append(toIndentedString(_2020)).append("\n");
    sb.append("    _2019: ").append(toIndentedString(_2019)).append("\n");
    sb.append("    _2018: ").append(toIndentedString(_2018)).append("\n");
    sb.append("    _2017: ").append(toIndentedString(_2017)).append("\n");
    sb.append("    _2016: ").append(toIndentedString(_2016)).append("\n");
    sb.append("    _2015: ").append(toIndentedString(_2015)).append("\n");
    sb.append("    _2014: ").append(toIndentedString(_2014)).append("\n");
    sb.append("    _2013: ").append(toIndentedString(_2013)).append("\n");
    sb.append("    scriptName: ").append(toIndentedString(scriptName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
