/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.treasuryInfo.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseYieldCurveEntryItem
 */

public class ResponseYieldCurveEntryItem {
  @JsonProperty("maturity")
  private String maturity = null;

  @JsonProperty("yield")
  private Double yield = null;

  @JsonProperty("years")
  private Double years = null;

  public ResponseYieldCurveEntryItem maturity(String maturity) {
    this.maturity = maturity;
    return this;
  }

   /**
   * Get maturity
   * @return maturity
  **/
  public String getMaturity() {
    return maturity;
  }

  public void setMaturity(String maturity) {
    this.maturity = maturity;
  }

  public ResponseYieldCurveEntryItem yield(Double yield) {
    this.yield = yield;
    return this;
  }

   /**
   * Get yield
   * @return yield
  **/
  public Double getYield() {
    return yield;
  }

  public void setYield(Double yield) {
    this.yield = yield;
  }

  public ResponseYieldCurveEntryItem years(Double years) {
    this.years = years;
    return this;
  }

   /**
   * Get years
   * @return years
  **/
  public Double getYears() {
    return years;
  }

  public void setYears(Double years) {
    this.years = years;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseYieldCurveEntryItem Response_yieldCurveEntryItem = (ResponseYieldCurveEntryItem) o;
    return Objects.equals(this.maturity, Response_yieldCurveEntryItem.maturity) &&
        Objects.equals(this.yield, Response_yieldCurveEntryItem.yield) &&
        Objects.equals(this.years, Response_yieldCurveEntryItem.years);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maturity, yield, years);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseYieldCurveEntryItem {\n");
    
    sb.append("    maturity: ").append(toIndentedString(maturity)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("    years: ").append(toIndentedString(years)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
