/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.sectorperformance.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.financeai.sectorperformance.model.ResponsePerformance;
/**
 * ResponseSectorPerformanceEntryItem
 */

public class ResponseSectorPerformanceEntryItem {
  @JsonProperty("performance")
  private ResponsePerformance performance = null;

  @JsonProperty("sector")
  private String sector = null;

  public ResponseSectorPerformanceEntryItem performance(ResponsePerformance performance) {
    this.performance = performance;
    return this;
  }

   /**
   * Get performance
   * @return performance
  **/
  public ResponsePerformance getPerformance() {
    return performance;
  }

  public void setPerformance(ResponsePerformance performance) {
    this.performance = performance;
  }

  public ResponseSectorPerformanceEntryItem sector(String sector) {
    this.sector = sector;
    return this;
  }

   /**
   * Get sector
   * @return sector
  **/
  public String getSector() {
    return sector;
  }

  public void setSector(String sector) {
    this.sector = sector;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseSectorPerformanceEntryItem Response_sectorPerformanceEntryItem = (ResponseSectorPerformanceEntryItem) o;
    return Objects.equals(this.performance, Response_sectorPerformanceEntryItem.performance) &&
        Objects.equals(this.sector, Response_sectorPerformanceEntryItem.sector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(performance, sector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseSectorPerformanceEntryItem {\n");
    
    sb.append("    performance: ").append(toIndentedString(performance)).append("\n");
    sb.append("    sector: ").append(toIndentedString(sector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
