/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.sectorperformance.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponsePerformance
 */

public class ResponsePerformance {
  @JsonProperty("yearToDate")
  private Double yearToDate = null;

  @JsonProperty("fiveYear")
  private Double fiveYear = null;

  @JsonProperty("today")
  private Double today = null;

  @JsonProperty("lastMonth")
  private Double lastMonth = null;

  @JsonProperty("lastWeek")
  private Double lastWeek = null;

  @JsonProperty("threeYear")
  private Double threeYear = null;

  @JsonProperty("tenYear")
  private Double tenYear = null;

  public ResponsePerformance yearToDate(Double yearToDate) {
    this.yearToDate = yearToDate;
    return this;
  }

   /**
   * Get yearToDate
   * @return yearToDate
  **/
  public Double getYearToDate() {
    return yearToDate;
  }

  public void setYearToDate(Double yearToDate) {
    this.yearToDate = yearToDate;
  }

  public ResponsePerformance fiveYear(Double fiveYear) {
    this.fiveYear = fiveYear;
    return this;
  }

   /**
   * Get fiveYear
   * @return fiveYear
  **/
  public Double getFiveYear() {
    return fiveYear;
  }

  public void setFiveYear(Double fiveYear) {
    this.fiveYear = fiveYear;
  }

  public ResponsePerformance today(Double today) {
    this.today = today;
    return this;
  }

   /**
   * Get today
   * @return today
  **/
  public Double getToday() {
    return today;
  }

  public void setToday(Double today) {
    this.today = today;
  }

  public ResponsePerformance lastMonth(Double lastMonth) {
    this.lastMonth = lastMonth;
    return this;
  }

   /**
   * Get lastMonth
   * @return lastMonth
  **/
  public Double getLastMonth() {
    return lastMonth;
  }

  public void setLastMonth(Double lastMonth) {
    this.lastMonth = lastMonth;
  }

  public ResponsePerformance lastWeek(Double lastWeek) {
    this.lastWeek = lastWeek;
    return this;
  }

   /**
   * Get lastWeek
   * @return lastWeek
  **/
  public Double getLastWeek() {
    return lastWeek;
  }

  public void setLastWeek(Double lastWeek) {
    this.lastWeek = lastWeek;
  }

  public ResponsePerformance threeYear(Double threeYear) {
    this.threeYear = threeYear;
    return this;
  }

   /**
   * Get threeYear
   * @return threeYear
  **/
  public Double getThreeYear() {
    return threeYear;
  }

  public void setThreeYear(Double threeYear) {
    this.threeYear = threeYear;
  }

  public ResponsePerformance tenYear(Double tenYear) {
    this.tenYear = tenYear;
    return this;
  }

   /**
   * Get tenYear
   * @return tenYear
  **/
  public Double getTenYear() {
    return tenYear;
  }

  public void setTenYear(Double tenYear) {
    this.tenYear = tenYear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePerformance Response_performance = (ResponsePerformance) o;
    return Objects.equals(this.yearToDate, Response_performance.yearToDate) &&
        Objects.equals(this.fiveYear, Response_performance.fiveYear) &&
        Objects.equals(this.today, Response_performance.today) &&
        Objects.equals(this.lastMonth, Response_performance.lastMonth) &&
        Objects.equals(this.lastWeek, Response_performance.lastWeek) &&
        Objects.equals(this.threeYear, Response_performance.threeYear) &&
        Objects.equals(this.tenYear, Response_performance.tenYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yearToDate, fiveYear, today, lastMonth, lastWeek, threeYear, tenYear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePerformance {\n");
    
    sb.append("    yearToDate: ").append(toIndentedString(yearToDate)).append("\n");
    sb.append("    fiveYear: ").append(toIndentedString(fiveYear)).append("\n");
    sb.append("    today: ").append(toIndentedString(today)).append("\n");
    sb.append("    lastMonth: ").append(toIndentedString(lastMonth)).append("\n");
    sb.append("    lastWeek: ").append(toIndentedString(lastWeek)).append("\n");
    sb.append("    threeYear: ").append(toIndentedString(threeYear)).append("\n");
    sb.append("    tenYear: ").append(toIndentedString(tenYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
