/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.kxAiAssistPromptResp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseDocsEntryItem
 */

public class ResponseDocsEntryItem {
  @JsonProperty("__nn_distance")
  private Double __nn_distance = null;

  @JsonProperty("Type")
  private String Type = null;

  @JsonProperty("Symbol")
  private String Symbol = null;

  @JsonProperty("Text")
  private String Text = null;

  @JsonProperty("Chunk")
  private Integer Chunk = null;

  @JsonProperty("int")
  private Integer _int = null;

  @JsonProperty("Date")
  private String Date = null;

  @JsonProperty("Source")
  private String Source = null;

  public ResponseDocsEntryItem __nn_distance(Double __nn_distance) {
    this.__nn_distance = __nn_distance;
    return this;
  }

   /**
   * Get __nn_distance
   * @return __nn_distance
  **/
  public Double getNnDistance() {
    return __nn_distance;
  }

  public void setNnDistance(Double __nn_distance) {
    this.__nn_distance = __nn_distance;
  }

  public ResponseDocsEntryItem Type(String Type) {
    this.Type = Type;
    return this;
  }

   /**
   * Get Type
   * @return Type
  **/
  public String getType() {
    return Type;
  }

  public void setType(String Type) {
    this.Type = Type;
  }

  public ResponseDocsEntryItem Symbol(String Symbol) {
    this.Symbol = Symbol;
    return this;
  }

   /**
   * Get Symbol
   * @return Symbol
  **/
  public String getSymbol() {
    return Symbol;
  }

  public void setSymbol(String Symbol) {
    this.Symbol = Symbol;
  }

  public ResponseDocsEntryItem Text(String Text) {
    this.Text = Text;
    return this;
  }

   /**
   * Get Text
   * @return Text
  **/
  public String getText() {
    return Text;
  }

  public void setText(String Text) {
    this.Text = Text;
  }

  public ResponseDocsEntryItem Chunk(Integer Chunk) {
    this.Chunk = Chunk;
    return this;
  }

   /**
   * Get Chunk
   * @return Chunk
  **/
  public Integer getChunk() {
    return Chunk;
  }

  public void setChunk(Integer Chunk) {
    this.Chunk = Chunk;
  }

  public ResponseDocsEntryItem _int(Integer _int) {
    this._int = _int;
    return this;
  }

   /**
   * Get _int
   * @return _int
  **/
  public Integer getInt() {
    return _int;
  }

  public void setInt(Integer _int) {
    this._int = _int;
  }

  public ResponseDocsEntryItem Date(String Date) {
    this.Date = Date;
    return this;
  }

   /**
   * Get Date
   * @return Date
  **/
  public String getDate() {
    return Date;
  }

  public void setDate(String Date) {
    this.Date = Date;
  }

  public ResponseDocsEntryItem Source(String Source) {
    this.Source = Source;
    return this;
  }

   /**
   * Get Source
   * @return Source
  **/
  public String getSource() {
    return Source;
  }

  public void setSource(String Source) {
    this.Source = Source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDocsEntryItem Response_docsEntryItem = (ResponseDocsEntryItem) o;
    return Objects.equals(this.__nn_distance, Response_docsEntryItem.__nn_distance) &&
        Objects.equals(this.Type, Response_docsEntryItem.Type) &&
        Objects.equals(this.Symbol, Response_docsEntryItem.Symbol) &&
        Objects.equals(this.Text, Response_docsEntryItem.Text) &&
        Objects.equals(this.Chunk, Response_docsEntryItem.Chunk) &&
        Objects.equals(this._int, Response_docsEntryItem._int) &&
        Objects.equals(this.Date, Response_docsEntryItem.Date) &&
        Objects.equals(this.Source, Response_docsEntryItem.Source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(__nn_distance, Type, Symbol, Text, Chunk, _int, Date, Source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDocsEntryItem {\n");
    
    sb.append("    __nn_distance: ").append(toIndentedString(__nn_distance)).append("\n");
    sb.append("    Type: ").append(toIndentedString(Type)).append("\n");
    sb.append("    Symbol: ").append(toIndentedString(Symbol)).append("\n");
    sb.append("    Text: ").append(toIndentedString(Text)).append("\n");
    sb.append("    Chunk: ").append(toIndentedString(Chunk)).append("\n");
    sb.append("    _int: ").append(toIndentedString(_int)).append("\n");
    sb.append("    Date: ").append(toIndentedString(Date)).append("\n");
    sb.append("    Source: ").append(toIndentedString(Source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
