/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.kxAiAssistPromptResp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.financeai.kxAiAssistPromptResp.model.ResponseDocsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("date_range")
  private List<String> date_range = new ArrayList<>();

  @JsonProperty("types")
  private List<String> types = new ArrayList<>();

  @JsonProperty("docs")
  private List<ResponseDocsEntryItem> docs = new ArrayList<>();

  @JsonProperty("refined_prompt")
  private String refined_prompt = null;

  @JsonProperty("keyword")
  private String keyword = null;

  @JsonProperty("symbols")
  private List<String> symbols = new ArrayList<>();

  public RootResponse date_range(List<String> date_range) {
    this.date_range = date_range;
    return this;
  }

  public RootResponse addDateRangeItem(String date_rangeItem) {
    this.date_range.add(date_rangeItem);
    return this;
  }

   /**
   * Get date_range
   * @return date_range
  **/
  public List<String> getDateRange() {
    return date_range;
  }

  public void setDateRange(List<String> date_range) {
    this.date_range = date_range;
  }

  public RootResponse types(List<String> types) {
    this.types = types;
    return this;
  }

  public RootResponse addTypesItem(String typesItem) {
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  public List<String> getTypes() {
    return types;
  }

  public void setTypes(List<String> types) {
    this.types = types;
  }

  public RootResponse docs(List<ResponseDocsEntryItem> docs) {
    this.docs = docs;
    return this;
  }

  public RootResponse addDocsItem(ResponseDocsEntryItem docsItem) {
    this.docs.add(docsItem);
    return this;
  }

   /**
   * Get docs
   * @return docs
  **/
  public List<ResponseDocsEntryItem> getDocs() {
    return docs;
  }

  public void setDocs(List<ResponseDocsEntryItem> docs) {
    this.docs = docs;
  }

  public RootResponse refined_prompt(String refined_prompt) {
    this.refined_prompt = refined_prompt;
    return this;
  }

   /**
   * Get refined_prompt
   * @return refined_prompt
  **/
  public String getRefinedPrompt() {
    return refined_prompt;
  }

  public void setRefinedPrompt(String refined_prompt) {
    this.refined_prompt = refined_prompt;
  }

  public RootResponse keyword(String keyword) {
    this.keyword = keyword;
    return this;
  }

   /**
   * Get keyword
   * @return keyword
  **/
  public String getKeyword() {
    return keyword;
  }

  public void setKeyword(String keyword) {
    this.keyword = keyword;
  }

  public RootResponse symbols(List<String> symbols) {
    this.symbols = symbols;
    return this;
  }

  public RootResponse addSymbolsItem(String symbolsItem) {
    this.symbols.add(symbolsItem);
    return this;
  }

   /**
   * Get symbols
   * @return symbols
  **/
  public List<String> getSymbols() {
    return symbols;
  }

  public void setSymbols(List<String> symbols) {
    this.symbols = symbols;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.date_range, RootResponse.date_range) &&
        Objects.equals(this.types, RootResponse.types) &&
        Objects.equals(this.docs, RootResponse.docs) &&
        Objects.equals(this.refined_prompt, RootResponse.refined_prompt) &&
        Objects.equals(this.keyword, RootResponse.keyword) &&
        Objects.equals(this.symbols, RootResponse.symbols);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date_range, types, docs, refined_prompt, keyword, symbols);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    date_range: ").append(toIndentedString(date_range)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    docs: ").append(toIndentedString(docs)).append("\n");
    sb.append("    refined_prompt: ").append(toIndentedString(refined_prompt)).append("\n");
    sb.append("    keyword: ").append(toIndentedString(keyword)).append("\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
