/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.topGainersLosers.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("dailyChange")
  private String dailyChange = null;

  @JsonProperty("scriptName")
  private String scriptName = null;

  @JsonProperty("weeklyChange")
  private String weeklyChange = null;

  public ResponseRootResponseROOTEntryItem dailyChange(String dailyChange) {
    this.dailyChange = dailyChange;
    return this;
  }

   /**
   * Get dailyChange
   * @return dailyChange
  **/
  public String getDailyChange() {
    return dailyChange;
  }

  public void setDailyChange(String dailyChange) {
    this.dailyChange = dailyChange;
  }

  public ResponseRootResponseROOTEntryItem scriptName(String scriptName) {
    this.scriptName = scriptName;
    return this;
  }

   /**
   * Get scriptName
   * @return scriptName
  **/
  public String getScriptName() {
    return scriptName;
  }

  public void setScriptName(String scriptName) {
    this.scriptName = scriptName;
  }

  public ResponseRootResponseROOTEntryItem weeklyChange(String weeklyChange) {
    this.weeklyChange = weeklyChange;
    return this;
  }

   /**
   * Get weeklyChange
   * @return weeklyChange
  **/
  public String getWeeklyChange() {
    return weeklyChange;
  }

  public void setWeeklyChange(String weeklyChange) {
    this.weeklyChange = weeklyChange;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this.dailyChange, Response_RootResponseROOTEntryItem.dailyChange) &&
        Objects.equals(this.scriptName, Response_RootResponseROOTEntryItem.scriptName) &&
        Objects.equals(this.weeklyChange, Response_RootResponseROOTEntryItem.weeklyChange);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dailyChange, scriptName, weeklyChange);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    dailyChange: ").append(toIndentedString(dailyChange)).append("\n");
    sb.append("    scriptName: ").append(toIndentedString(scriptName)).append("\n");
    sb.append("    weeklyChange: ").append(toIndentedString(weeklyChange)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
