/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.financeai.heatMap.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("parent")
  private String parent = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("colorValue")
  private Integer colorValue = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("value")
  private Integer value = null;

  public ResponseRootResponseROOTEntryItem parent(String parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  public String getParent() {
    return parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public ResponseRootResponseROOTEntryItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponseRootResponseROOTEntryItem colorValue(Integer colorValue) {
    this.colorValue = colorValue;
    return this;
  }

   /**
   * Get colorValue
   * @return colorValue
  **/
  public Integer getColorValue() {
    return colorValue;
  }

  public void setColorValue(Integer colorValue) {
    this.colorValue = colorValue;
  }

  public ResponseRootResponseROOTEntryItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseRootResponseROOTEntryItem value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this.parent, Response_RootResponseROOTEntryItem.parent) &&
        Objects.equals(this.name, Response_RootResponseROOTEntryItem.name) &&
        Objects.equals(this.colorValue, Response_RootResponseROOTEntryItem.colorValue) &&
        Objects.equals(this.id, Response_RootResponseROOTEntryItem.id) &&
        Objects.equals(this.value, Response_RootResponseROOTEntryItem.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, name, colorValue, id, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    colorValue: ").append(toIndentedString(colorValue)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
